version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: movie-review-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_db
      POSTGRES_PASSWORD: movie_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: