spring.application.name=movie-review-api
spring.datasource.url=jdbc:postgresql://localhost:5433/movie_db
spring.datasource.username=movie_db
spring.datasource.password=movie_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.seed.enabled=true
